name: cargo-task

on: [ push ]

jobs:

 test:
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [
     ubuntu-latest,
     macos-latest,
     windows-latest,
    ]
    toolchain: [
     stable,
    ]
  steps:
   - uses: actions/checkout@v2

   - uses: actions-rs/toolchain@v1
     with:
       toolchain: ${{ matrix.toolchain }}

   # bootstrap our own cargo-task default task
   - uses: actions-rs/cargo@v1
     with:
       command: run
       args: -- -- ci
